package: binstar
engine:
 - python=2.7
 - python=3.3

install:
  - pip install -r requirements.txt
  - pip install coverage mock
test:
  - python setup.py develop
  - python binstar_client/tests/runtests.py

script:
  - conda build .

build_targets:
  channels: 
    - dev
    - "%(branch)s"
  files: dist/*.tar.bz2
