package: binstar-build
engine:
  - python=2.7
platform:
  - linux-64
  - osx-64

install:
  - conda install binstar pip setuptools
  - pip install coverage mock

script:
  - conda build conda.recipe

build_targets: conda
