package: binstar
engine:
  - python=2.7
platform:
  - linux-64
  - osx-64

install:
  - pip install -r requirements.txt
  - pip install coverage mock
test:
  - python setup.py develop
  - python binstar_client/tests/runtests.py

script:
  - conda build .

build_targets:
  channels:
    - dev
    - "%(branch)s"
  files: dist/*.tar.bz2
