
package:
  name: binstar-build
  version: 0.0.0
build:
  number: 0
  pin_depends: record
  script:
    - cd $RECIPE_DIR/..
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - anaconda-client
    - pywin32 [win]

about:
  home: http://github.com/Binstar/binstar_client
  license: MIT
